import os
import io
import time
import base64
import gc

import numpy as np
from PIL import Image
from flask import Flask, request, jsonify, render_template
import tensorflow as tf

import models
from dark_channel_prior import dehaze_dcp

from utils import (
    IMG_SIZE, to_uint8, compute_all_metrics,
    detect_weather, haze_density, recommend_model, preprocess_for_weather,
)

app = Flask(__name__)

SAVE_DIR = "saved_models"
MODEL_KEYS = {
    "AOD-Net": "aod_net.keras",
    "Attention-UNet": "attention_unet.keras",
    "GAN": "gan_generator.keras",
}
DCP_NAME = "DCP"


def get_model(display_name):
    """Load a trained model fresh each time (no persistent caching).

    Render's free tier has only 512MB RAM. Keeping multiple TensorFlow
    models loaded simultaneously (as a cache would) reliably exceeds this
    and causes OOM crashes, which show up as confusing 'expected N
    variables, received 0' errors on the NEXT request rather than a clear
    out-of-memory message. Loading fresh and freeing immediately after use
    (see run_model below) trades some speed for staying within memory
    limits — the right tradeoff for a free-tier demo deployment.
    """
    path = os.path.join(SAVE_DIR, MODEL_KEYS[display_name])
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"'{display_name}' has not been trained yet. Run: "
            f"python train.py --model {MODEL_KEYS[display_name].replace('.keras','')}"
        )
    # safe_mode=False is required because AOD-Net uses a Lambda layer for its
    # K(x)*I(x) - K(x) + 1 formula; this is safe since we're loading our own
    # trained model, not one from an untrusted source.
    return tf.keras.models.load_model(path, compile=False, safe_mode=False)


MAX_DISPLAY_DIM = 1024  # cap upscaled display size so huge photos don't bloat the response


def decode_upload(file_storage):
    img = Image.open(file_storage.stream).convert("RGB")
    original_size = img.size  # (width, height), before resizing for the model

    # Cap display size for very large uploads
    w, h = original_size
    if max(w, h) > MAX_DISPLAY_DIM:
        scale = MAX_DISPLAY_DIM / max(w, h)
        original_size = (int(w * scale), int(h * scale))

    resized = img.resize(IMG_SIZE)
    return np.asarray(resized, dtype=np.float32) / 255.0, original_size


def encode_image(img_float, display_size=None):
    """display_size: optional (width, height) to upscale to before sending —
    purely cosmetic (matches the original upload's dimensions), does not add
    real detail beyond what the 256x256 model produced."""
    img = Image.fromarray(to_uint8(img_float))
    if display_size is not None and display_size != img.size:
        img = img.resize(display_size, Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("utf-8")


def run_model(display_name, hazy_img):
    start = time.time()
    if display_name == DCP_NAME:
        dehazed = dehaze_dcp(hazy_img)
    else:
        model = get_model(display_name)
        dehazed = model.predict(hazy_img[None, ...], verbose=0)[0]
        # Free the model and clear TensorFlow's backend session immediately —
        # critical on memory-constrained deployments (e.g. Render free tier's
        # 512MB limit). Without this, repeated requests accumulate memory
        # until the process gets OOM-killed.
        del model
        tf.keras.backend.clear_session()
        gc.collect()
    elapsed_ms = (time.time() - start) * 1000
    dehazed = np.clip(dehazed, 0, 1)
    return dehazed, elapsed_ms

COMPARE_DIR = os.path.join("outputs", "compare")


@app.route("/api/compare")
def api_compare():
    """Reads outputs/compare/comparison.csv (written by evaluate.py) and
    returns it as JSON rows, plus a flag for whether the bar chart image
    exists, so the Compare tab can render real results instead of static
    placeholder text."""
    csv_path = os.path.join(COMPARE_DIR, "comparison.csv")
    chart_path = os.path.join(COMPARE_DIR, "comparison_bar_chart.png")

    if not os.path.exists(csv_path):
        return jsonify({
            "available": False,
            "message": "No comparison results yet. Run 'python evaluate.py' first, "
                       "then refresh this tab."
        })

    import pandas as pd
    df = pd.read_csv(csv_path)
    rows = df.to_dict(orient="records")

    return jsonify({
        "available": True,
        "rows": rows,
        "chart_available": os.path.exists(chart_path),
    })


@app.route("/api/compare/chart")
def api_compare_chart():
    """Serves the bar chart PNG generated by evaluate.py."""
    from flask import send_file
    chart_path = os.path.join(COMPARE_DIR, "comparison_bar_chart.png")
    if not os.path.exists(chart_path):
        return jsonify({"error": "Chart not found. Run evaluate.py first."}), 404
    return send_file(chart_path, mimetype="image/png")

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/models")
def api_models():
    available = {name: os.path.exists(os.path.join(SAVE_DIR, fn))
                 for name, fn in MODEL_KEYS.items()}
    available[DCP_NAME] = True  # classical method, always available
    return jsonify(available)


@app.route("/api/dehaze", methods=["POST"])
def api_dehaze():
    file = request.files.get("image")
    model_choice = request.form.get("model", "Attention-UNet")
    auto_select = request.form.get("auto_select", "false") == "true"

    if file is None:
        return jsonify({"error": "No image uploaded"}), 400

    hazy, original_size = decode_upload(file)
    weather = detect_weather(hazy)
    density = haze_density(hazy)

    processed = preprocess_for_weather(hazy, weather)

    if auto_select:
        model_choice = {
            "aod_net": "AOD-Net",
            "attention_unet": "Attention-UNet",
            "gan_generator": "GAN",
        }[recommend_model(hazy)]
        # DCP is intentionally excluded from Auto Select — it's offered as a
        # manual classical baseline for comparison, not a recommended default.

    try:
        dehazed, elapsed_ms = run_model(model_choice, processed)
    except FileNotFoundError as e:
        return jsonify({"error": str(e)}), 400

    # Self-referential metrics (no ground truth available for user uploads):
    # compare dehazed output against the input to report entropy/edge gains.
    metrics = compute_all_metrics(dehazed, hazy, elapsed_ms)

    return jsonify({
        "input_image": encode_image(hazy, original_size),
        "output_image": encode_image(dehazed, original_size),
        "model_used": model_choice,
        "weather": weather,
        "haze_density": density,
        "metrics": metrics,
    })


@app.route("/api/dehaze_all", methods=["POST"])
def api_dehaze_all():
    file = request.files.get("image")
    if file is None:
        return jsonify({"error": "No image uploaded"}), 400

    hazy, original_size = decode_upload(file)
    weather = detect_weather(hazy)
    processed = preprocess_for_weather(hazy, weather)

    results = {}
    for name in list(MODEL_KEYS.keys()) + [DCP_NAME]:
        try:
            dehazed, elapsed_ms = run_model(name, processed)
            metrics = compute_all_metrics(dehazed, hazy, elapsed_ms)
            results[name] = {
                "output_image": encode_image(dehazed, original_size),
                "metrics": metrics,
            }
        except FileNotFoundError as e:
            results[name] = {"error": str(e)}

    return jsonify({
        "input_image": encode_image(hazy, original_size),
        "weather": weather,
        "results": results,
    })


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    debug_mode = os.environ.get("FLASK_DEBUG", "true").lower() == "true"
    app.run(host="0.0.0.0", port=port, debug=debug_mode)